### ISSUE TITLE
Methods in DumbMath need javadoc comments

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#1]
There should be javadoc comments for all methods in DumbMath. They don't need to be super-descriptive, just summarize the method and the return value.

**Comment by chenhe95** [comment]
I am working on this

**Comment by chenhe95** [comment]
Pull request submitted

**Comment by nfallen** [comment]
Can you put the link to the PR here?

**Comment by chenhe95** [comment]
https://github.com/cis-upenn/fun-with-github/pull/21

**Comment by nfallen** [comment]
Please resolve the merge conflict!

**Comment by chenhe95** [comment]
Merge conflict resolved
