### ISSUE TITLE
DumbString.allDigits should be static

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#11]
Please change DumbString.addDigits to be a static method.

**Comment by miafg** [comment]
I can work on this.

**Comment by miafg** [comment]
Created a pull request

**Comment by nfallen** [comment]
can you post a link to the PR here?

**Comment by miafg** [comment]
https://github.com/cis-upenn/fun-with-github/pull/19

Changed the test cases too.
