### ISSUE TITLE
DumbString.addDigits should return false if input is null

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#12]
Right now it throws an exception, but it should return false in this case.

**Comment by JudyWeng** [comment]
:) working on this issue

**Comment by ChrisMurphyOnline** [comment]
Sorry, it's DumbString.**all**Digits, not addDigits

**Comment by JudyWeng** [comment]
Added pull request at #29

**Comment by ChrisMurphyOnline** [comment]
Please resolve the merge conflict
