### ISSUE TITLE
lettersInCommon HAS A BUG!!!!

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#14]
The lettersInCommon method double-counts chars that appear in the first parameter. It should only count the distinct chars in common, e.g. "aa" and "ab" only have one char in common ('a') but the method returns 2.

The DumbStringTest.testLettersInCommonDoubleCount test reveals this bug.

**Comment by jkarno** [comment]
Working on this

**Comment by jkarno** [comment]
Pull request has been submitted: https://github.com/cis-upenn/fun-with-github/pull/25
