### ISSUE TITLE
need test for DumbString.lettersInCommon where one argument is null

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#15]
The method should return -1 in that case.

**Comment by Dylan-Brown** [comment]
I'll do it

**Comment by Dylan-Brown** [comment]
So  it seems to me that this is already tested for, since there is a line that checks for if either argument is null, then return negative 1. So I'm confused why this is an issue?

**Comment by ChrisMurphyOnline** [comment]
Sorry, by "test" I meant "a JUnit test case"

**Comment by Dylan-Brown** [comment]
Done

**Comment by ChrisMurphyOnline** [comment]
Can you please include a link to the PR?

**Comment by Dylan-Brown** [comment]
https://github.com/cis-upenn/fun-with-github/pull/28
