### ISSUE TITLE
check for underflow in DumbMath.add

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#2]
The DumbMath.add method checks for overflow but should also check for underflow, i.e. when you add two negative numbers and get a positive number. 

If that happens, it should throw an ArithmeticException with a similar message as for underflow.

**Comment by kchen17** [comment]
I'll work on this

**Comment by racheldchan** [comment]
did this one. sorry i didn't comment earlier.

**Comment by ChrisMurphyOnline** [comment]
Please include a link to the PR.

**Comment by kchen17** [comment]
Not sure if @racheldchan already has a PR up, but [here's mine](https://github.com/cis-upenn/fun-with-github/pull/31).

**Comment by racheldchan** [comment]
https://github.com/cis-upenn/fun-with-github/pull/31

**Comment by ChrisMurphyOnline** [comment]
Actually yours was #30.... :-)
