### ISSUE TITLE
Need DumbMath.add(double, double)

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#3]
DumbMath has an "add" method that takes two ints, but also needs a method that takes two doubles and returns their sum as a double.

**Comment by reedrosenbluth** [comment]
working on it!

**Comment by reedrosenbluth** [comment]
PR: https://github.com/cis-upenn/fun-with-github/pull/18

**Comment by ChrisMurphyOnline** [comment]
Thanks! Can you please work on the test case in Issue #8 too?
