### ISSUE TITLE
overflow/underflow tests for add(double, double)

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#32]
DumbMathTest needs to have two test cases for the add(double, double) method: one that checks to see that overflow is properly handled, and one that checks that underflow is properly handled.

**Comment by leesafini** [comment]
I'll do this!

**Comment by nfallen** [comment]
Thanks!

**Comment by leesafini** [comment]
I had to make a change in the add method for two doubles, because I think I'm ready to pull.

**Comment by nfallen** [comment]
Thanks for figuring that out! Can you link to the PR from this issue?

**Comment by leesafini** [comment]
#35

**Comment by nfallen** [comment]
Thanks!
