### ISSUE TITLE
Test add(double, double) when both arguments are negative

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#33]
There needs to be a test in DumbMathTest that checks that add(double, double) works correctly when both arguments are negative. This should be called testAddDoubleNegativeAndNegative.

As a result, please also change the name of the testAddDouble method to testAddDoublePositiveAndPositive.

**Comment by ameliagoodman** [comment]
i can work on this

**Comment by nfallen** [comment]
Sounds good!

**Comment by ameliagoodman** [comment]
https://github.com/cis-upenn/fun-with-github/pull/34
