### ISSUE TITLE
DumbMathTest.overflow does not adhere to convention

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#7]
The name of this method should start with "test" and should describe what is being tested here.

**Comment by sumitshyamsukha** [comment]
I'm working on this issue.

**Comment by sumitshyamsukha** [comment]
Fixed in https://github.com/cis-upenn/fun-with-github/pull/23

**Comment by nfallen** [comment]
thanks! for future reference it is easier to review if you just make two separate PRs for the different issues, no worries this time though!
