### ISSUE TITLE
Need test case for DumbMath.add(double, double)

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#8]
Once Issue #3 is done, we need a test case in DumbMathTest that checks normal operation.

**Comment by reedrosenbluth** [comment]
working on it

**Comment by reedrosenbluth** [comment]
https://github.com/cis-upenn/fun-with-github/pull/24

**Comment by ChrisMurphyOnline** [comment]
Please resolve the merge conflict

**Comment by reedrosenbluth** [comment]
done
