### ISSUE TITLE
need test for addFraction in which a denominator is zero

### ISSUE THREAD

**Issue by ChrisMurphyOnline** [cis-upenn/fun-with-github#9]
There should be a test case in DumbMathTest that checks that an IllegalArgumentException is thrown if one of the denominator arguments is zero.

**Comment by sumitshyamsukha** [comment]
I'm working on this issue.

**Comment by sumitshyamsukha** [comment]
I've added a PR at: https://github.com/cis-upenn/fun-with-github/pull/23
